Repository ca-cwds/intake, pull requests merged in 2019-01, with the labels that each got.

#1026 Disable accessibility check - feature person age validation
  spec/features/screening/validations/person_age_validation_spec.rb
  spec/spec_helper.rb
Labels: patch

#1027 update react dom version to avoid cross-site scripting vulnerability
  package.json
  yarn.lock
Labels: patch

#1028 FIT-355-Standardized the Jenkins File and added the Smoke Test
  Jenkinsfile
Labels: patch

#1030 Fix for Integration Smoke test
  Jenkinsfile
Labels: patch

#1031 Fit 355 Fix for Slack notification
  Jenkinsfile
Labels: patch

#1032 Added @Field to pipelinestatus to make it avilable on Jenkins file
  Jenkinsfile
Labels: patch

#1033 SNAP-817 Increased fuse threshold to match and some design change
  app/javascript/selectors/peopleSearchSelectors.js
  spec/javascripts/components/common/PersonSuggestionSpec.jsx
  spec/javascripts/selectors/peopleSearchSelectorsSpec.js
Labels: patch

#1034 SNAP-860 Fix Hispanic/Latino mapping
  app/javascript/reducers/peopleFormReducer.js
  app/javascript/selectors/screening/personFormSelectors.js
  app/javascript/selectors/screening/personShowSelectors.js
  app/models/participant.rb
  spec/controllers/api/v1/participants_controller_spec.rb
  spec/features/screening/participant/create_participant_spec.rb
  spec/features/screening/participant/editing_participant_spec.rb
  spec/features/screening/participant/race_ethnicity_spec.rb
  spec/features/screening/participant/show_participant_spec.rb
  spec/features/screening/people_and_role_navigation_spec.rb
  spec/javascripts/containers/screenings/PersonShowContainerSpec.jsx
  spec/javascripts/reducers/peopleFormReducerSpec.js
  spec/javascripts/selectors/screening/personFormSelectorSpec.js
  spec/javascripts/selectors/screening/personShowSelectorsSpec.js
  spec/javascripts/store/storeSpec.js
  spec/models/participant_spec.rb
Labels: patch

#1035 SNAP-837 Add phone number extension
  app/javascript/reducers/peopleFormReducer.js
  app/javascript/selectors/screening/personShowSelectors.js
  app/javascript/views/people/PhoneNumbersShow.jsx
  spec/javascripts/reducers/peopleFormReducerSpec.js
  spec/javascripts/selectors/screening/personShowSelectorsSpec.js
  spec/javascripts/views/people/PhoneNumbersShowSpec.jsx
Labels: minor

#1036 SNAP-830 search results menu should be visible
  app/javascript/common/search/Autocompleter.jsx
  spec/features/screening/participant/search_participant_spec.rb
  spec/features/snapshot/create_snapshot_spec.rb
Labels: minor

#1037 SNAP-865 Bug Fix Add Participant More than Once in Snapshot
  .gitignore
  app/javascript/common/Relationships.jsx
  app/javascript/common/RelationshipsCard.jsx
  app/javascript/common/relationship/AttachLink.jsx
  app/javascript/containers/snapshot/RelationshipsContainer.js
  app/javascript/snapshots/SnapshotPage.jsx
  spec/javascripts/components/common/RelationshipsSpec.jsx
  spec/javascripts/components/common/relationship/AttachLinkSpec.jsx
Labels: bug, minor
