Repository ca-cwds/intake, pull requests merged in 2019-05, with the labels that each got.

#1120 Fixed mouse caret bug for firefox
  app/javascript/common/MaskedInputField.jsx
  spec/javascripts/components/common/MaskedInputFieldSpec.jsx
Labels: bug, minor

#1119 Refactor on blur and on focus field validation actions
  app/javascript/actions/peopleSearchActions.js
  app/javascript/common/DateField.jsx
  app/javascript/common/HyphenatedMaskedInput.jsx
  app/javascript/common/MaskedInputField.jsx
  app/javascript/common/search/MaskedSearchInput.jsx
  app/javascript/common/search/PersonSearchAgeGenderNumbersGroup.jsx
  app/javascript/common/search/PersonSearchNumbersAgeGroup.jsx
  app/javascript/common/search/age/AgeUnitForm.jsx
  app/javascript/common/search/age/DateOfBirthDateField.jsx
  app/javascript/containers/common/PersonSearchFormContainer.js
  app/javascript/reducers/peopleSearchReducer.js
  app/javascript/selectors/peopleSearchSelectors.js
  app/javascript/utils/textFormatter.js
  spec/javascripts/actions/peopleSearchActionsSpec.js
  spec/javascripts/components/common/DateFieldSpec.jsx
  spec/javascripts/components/common/HyphenatedMaskedInputSpec.jsx
  spec/javascripts/components/common/MaskedInputFieldSpec.jsx
  spec/javascripts/components/common/search/MaskedSearchInputSpec.jsx
  spec/javascripts/components/common/search/PersonSearchAgeGenderNumbersGroupSpec.jsx
  spec/javascripts/components/common/search/age/AgeUnitFormSpec.jsx
  spec/javascripts/components/common/search/age/DateOfBirthDateFieldSpec.jsx
  spec/javascripts/reducers/peopleSearchReducerSpec.js
  spec/javascripts/selectors/peopleSearchSelectorsSpec.js
  spec/javascripts/store/storeSpec.js
  spec/javascripts/utils/textFormatterSpec.js
Labels: patch

#1122 SNAP-1062 Search By Last Name Only
  app/repositories/base_query_builder.rb
  app/repositories/query_builder.rb
  app/services/person_search_by_address.rb
  app/services/person_search_by_last_name_query_builder.rb
  spec/repositories/query_builder_spec.rb
  spec/services/person_search_by_address_spec.rb
  spec/services/person_search_by_last_name_query_builder_spec.rb
  spec/services/person_search_by_name_query_builder_part_one_spec.rb
  spec/services/person_search_by_name_query_builder_part_two_spec.rb
  spec/support/helpers/person_search_by_address_helper.rb
  spec/support/helpers/person_search_by_last_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_part_one_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_part_two_helper.rb
  spec/support/helpers/person_search_query_builder_helper.rb
  spec/support/person_search_result_builder.rb
Labels: minor

#1128 SNAP-1062 Last Name Query Update
  app/services/person_search_by_last_name_query_builder.rb
  spec/support/helpers/person_search_by_last_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
Labels: patch

#1125 SNAP-1071 - Refactor Search Related Property Names and Methods
  app/javascript/common/search/Autocompleter.jsx
  app/javascript/common/search/MaskedSearchInput.jsx
  app/javascript/common/search/PersonSearchAgeGenderNumbersGroup.jsx
  app/javascript/common/search/PersonSearchNameGroup.jsx
  app/javascript/common/search/age/AgeSearchFields.jsx
  app/javascript/common/search/age/AgeUnitForm.jsx
  app/javascript/common/search/age/DateOfBirthDateField.jsx
  app/javascript/common/search/sexatbirth/GenderSelect.jsx
  app/javascript/data/personSearch.js
  app/javascript/reducers/peopleSearchReducer.js
  app/javascript/selectors/peopleSearchSelectors.js
  spec/javascripts/components/common/search/AutocompleterSpec.jsx
  spec/javascripts/components/common/search/MaskedSearchInputSpec.jsx
  spec/javascripts/components/common/search/PersonSearchAgeGenderNumbersGroupSpec.jsx
  spec/javascripts/components/common/search/PersonSearchNameGroupSpec.jsx
  spec/javascripts/components/common/search/age/AgeSearchFieldsSpec.jsx
  spec/javascripts/components/common/search/age/AgeUnitFormSpec.jsx
  spec/javascripts/components/common/search/age/DateOfBirthDateFieldSpec.jsx
  spec/javascripts/components/common/search/sexatbirth/GenderSelectSpec.jsx
  spec/javascripts/reducers/peopleSearchReducerSpec.js
  spec/javascripts/sagas/fetchPeopleSearchSagaSpec.js
  spec/javascripts/sagas/loadMorePeopleSearchResultsSagaSpec.js
  spec/javascripts/selectors/peopleSearchSelectorsSpec.js
  spec/javascripts/store/storeSpec.js
Labels: minor

#1132 SNAP-1082 Last Name with Suffix Search Query
  app/helpers/query_builder_helper.rb
  app/repositories/base_query_builder.rb
  app/repositories/query_builder.rb
  app/services/person_search_by_last_name_query_builder.rb
  app/services/person_search_by_last_name_suffix_query_builder.rb
  app/services/person_search_by_name_query_builder_part_one.rb
  app/services/person_search_by_name_query_builder_part_two.rb
  spec/repositories/query_builder_spec.rb
  spec/services/person_search_by_last_name_suffix_query_builder_spec.rb
  spec/support/helpers/person_search_by_last_name_suffix_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/person_search_result_builder.rb
Labels: minor

#1133 SNAP-1062 Person Search By Last Name Update
  app/services/person_search_by_last_name_query_builder.rb
  spec/support/helpers/person_search_by_last_name_query_builder_helper.rb
Labels: patch

#1123 Snapshot Search Results Page
  app/assets/stylesheets/search.scss
  app/helpers/query_builder_helper.rb
  app/javascript/common/search/Autocompleter.jsx
  app/javascript/common/search/PersonSearchResults.jsx
  app/javascript/common/search/SearchResultsTable.jsx
  app/javascript/containers/snapshot/PersonSearchResultsContainer.js
  app/javascript/snapshots/SnapshotPage.jsx
  package.json
  spec/features/snapshot/create_snapshot_spec.rb
  spec/features/snapshot/history_of_involvement_spec.rb
  spec/features/snapshot/relationships_snapshot_spec.rb
  spec/features/snapshot/search_results_page_spec.rb
  spec/javascripts/components/SnapshotPageSpec.jsx
  spec/javascripts/components/common/search/PersonSearchResultsSpec.jsx
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/helpers/person_search_query_builder_helper.rb
  yarn.lock
Labels: minor

#1134 SNAP-984 Fix rspec test
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
Labels: patch

#1135 SNAP-984 Added column and links to name
  app/assets/stylesheets/search.scss
  app/javascript/common/search/SearchResultsTable.jsx
  spec/features/snapshot/create_snapshot_spec.rb
  spec/features/snapshot/search_results_page_spec.rb
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
Labels: minor

#1136 SNAP-984 Format Text in Search Results Table
  app/javascript/common/search/SearchResultsTable.jsx
  spec/features/snapshot/search_results_page_spec.rb
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
Labels: patch

#1137 SNAP-1068 Remove the snapshot intro component
  app/javascript/snapshots/SnapshotIntro.jsx
  app/javascript/snapshots/SnapshotPage.jsx
  spec/features/snapshot/create_snapshot_spec.rb
  spec/javascripts/components/SnapshotPageSpec.jsx
  spec/javascripts/components/snapshots/SnapshotIntroSpec.jsx
Labels: minor

#1138 Update Address Format in Data Grid;
  app/javascript/common/search/SearchResultsTable.jsx
  spec/features/snapshot/search_results_page_spec.rb
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
Labels: patch

#1139 SNAP-1081 Create a Client Detail Page
  app/assets/stylesheets/search.scss
  app/assets/stylesheets/shame_overrides.scss
  app/javascript/actions/actionTypes.js
  app/javascript/actions/snapshotActions.js
  app/javascript/common/app/Routes.jsx
  app/javascript/common/search/Autocompleter.jsx
  app/javascript/common/search/PersonSearchResults.jsx
  app/javascript/common/search/SearchResultsTable.jsx
  app/javascript/sagas/index.js
  app/javascript/sagas/viewSnapshotDetailSaga.js
  app/javascript/snapshots/SnapshotDetailPage.jsx
  app/javascript/snapshots/SnapshotPage.jsx
  app/javascript/utils/dateFormatter.js
  app/javascript/views/history/HistoryTable.jsx
  app/javascript/views/people/PersonSearchForm.jsx
  spec/features/snapshot/history_of_involvement_spec.rb
  spec/features/snapshot/relationships_snapshot_spec.rb
  spec/javascripts/actions/snapshotActionsSpec.js
  spec/javascripts/components/SnapshotDetailPageSpec.jsx
  spec/javascripts/components/SnapshotPageSpec.jsx
  spec/javascripts/components/common/search/AutocompleterSpec.jsx
  spec/javascripts/components/common/search/PersonSearchResultsSpec.jsx
  spec/javascripts/sagas/viewSnapshotDetailSagaSpec.js
  spec/javascripts/utils/dateFormatterSpec.js
  spec/javascripts/views/history/HistoryTableSpec.jsx
  spec/javascripts/views/people/PersonSearchFormSpec.jsx
Labels: minor

#1142 SNAP-1066 Updte Last and First Name Query
  app/services/person_search_by_name_query_builder_part_one.rb
  app/services/person_search_by_name_query_builder_part_two.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_part_one_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_part_two_helper.rb
Labels: patch

#1143 SNAP-1062 Update Last Name Query
  app/services/person_search_by_last_name_query_builder.rb
  spec/support/helpers/person_search_by_last_name_query_builder_helper.rb
Labels: patch

#1144 SNAP-1082 Update Last Name with Suffix Query
  app/services/person_search_by_last_name_suffix_query_builder.rb
  spec/support/helpers/person_search_by_last_name_suffix_query_builder_helper.rb
Labels: patch

#1145 SNAP-1081 Update Snapshot Detail Page UI
  app/javascript/actions/actionTypes.js
  app/javascript/actions/snapshotActions.js
  app/javascript/containers/snapshot/PersonCardContainer.js
  app/javascript/sagas/index.js
  app/javascript/sagas/viewSnapshotSearchSaga.js
  app/javascript/snapshots/SnapshotDetailPage.jsx
  spec/javascripts/components/SnapshotDetailPageSpec.jsx
  spec/javascripts/sagas/viewSnapshotSearchSagaSpec.js
  spec/javascripts/views/people/PersonCardHeaderSpec.jsx
Labels: minor

#1147 Fix Search Query Sort Parameters
  app/repositories/base_query_builder.rb
  spec/support/helpers/person_search_by_last_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_last_name_suffix_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_part_one_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_part_two_helper.rb
  spec/support/helpers/person_search_query_builder_helper.rb
Labels: patch

#1140 SNAP 984 PR2
  app/assets/stylesheets/search.scss
  app/controllers/api/v1/people_controller.rb
  app/helpers/query_builder_helper.rb
  app/javascript/actions/peopleSearchActions.js
  app/javascript/common/search/PersonSearchResults.jsx
  app/javascript/common/search/SearchResultsTable.jsx
  app/javascript/containers/snapshot/PersonSearchResultsContainer.js
  app/javascript/reducers/peopleSearchReducer.js
  app/javascript/sagas/fetchPeopleSearchSaga.js
  app/javascript/sagas/loadMorePeopleSearchResultsSaga.js
  app/javascript/selectors/peopleSearchSelectors.js
  app/repositories/base_query_builder.rb
  package.json
  spec/controllers/api/v1/people_controller_spec.rb
  spec/javascripts/actions/peopleSearchActionsSpec.js
  spec/javascripts/components/common/search/PersonSearchResultsSpec.jsx
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
  spec/javascripts/reducers/peopleSearchReducerSpec.js
  spec/javascripts/sagas/fetchPeopleSearchSagaSpec.js
  spec/javascripts/sagas/loadMorePeopleSearchResultsSagaSpec.js
  spec/javascripts/selectors/peopleSearchSelectorsSpec.js
  spec/javascripts/store/storeSpec.js
  spec/repositories/query_builder_spec.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/helpers/person_search_query_builder_helper.rb
  yarn.lock
Labels: minor

#1148 SNAP 984 Added case status
  app/javascript/common/search/SearchResultsTable.jsx
  app/javascript/selectors/peopleSearchSelectors.js
  app/repositories/base_query_builder.rb
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
  spec/javascripts/selectors/peopleSearchSelectorsSpec.js
  spec/support/helpers/query_builder_helper.rb
  spec/support/person_search_result_builder.rb
Labels: minor

#1149 SNAP-1055 Last Middle and First Name Query
  app/repositories/base_query_builder.rb
  app/repositories/query_builder.rb
  app/services/person_search_by_last_first_name_query_builder_part_one.rb
  app/services/person_search_by_last_first_name_query_builder_part_two.rb
  app/services/person_search_by_last_middle_first_name_query_builder_part_one.rb
  app/services/person_search_by_last_middle_first_name_query_builder_part_two.rb
  app/services/person_search_by_sex_at_birth_query_builder.rb
  spec/repositories/query_builder_spec.rb
  spec/services/person_search_by_last_first_name_query_builder_part_one_spec.rb
  spec/services/person_search_by_last_first_name_query_builder_part_two_spec.rb
  spec/services/person_search_by_last_middle_first_name_query_builder_part_one_spec.rb
  spec/services/person_search_by_last_middle_first_name_query_builder_part_two_spec.rb
  spec/services/person_search_by_name_query_builder_part_two_spec.rb
  spec/services/person_search_by_sex_at_birth_query_builder_spec.rb
  spec/support/helpers/person_search_by_approximate_age_query_builder_helper.rb
  spec/support/helpers/person_search_by_last_first_name_query_builder_part_one_helper.rb
  spec/support/helpers/person_search_by_last_first_name_query_builder_part_two_helper.rb
  spec/support/helpers/person_search_by_last_middle_first_name_query_builder_part_one_helper.rb
  spec/support/helpers/person_search_by_last_middle_first_name_query_builder_part_two_helper.rb
  spec/support/helpers/person_search_by_last_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_last_name_suffix_query_builder_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/helpers/person_search_by_sex_at_birth_query_builder_helper.rb
  spec/support/helpers/person_search_gender_query_builder_helper.rb
  spec/support/helpers/person_search_query_builder_helper.rb
  spec/support/helpers/person_search_ssn_query_builder_helper.rb
  spec/support/helpers/query_builder_helper.rb
  spec/support/person_search_result_builder.rb
Labels: minor

#1150 feature: remove attach h functionality
  app/javascript/common/Relationships.jsx
  spec/javascripts/components/common/RelationshipsSpec.jsx
Labels: patch

#1154 Lower Case Search Criteria on Search
  app/javascript/data/personSearch.js
  app/javascript/sagas/fetchPeopleSearchSaga.js
  spec/javascripts/sagas/fetchPeopleSearchSagaSpec.js
  spec/javascripts/sagas/loadMorePeopleSearchResultsSagaSpec.js
Labels: patch

#1152 SNAP-984 Added SP county and SP phone
  app/assets/stylesheets/search.scss
  app/javascript/common/search/SearchResultsTable.jsx
  app/javascript/selectors/peopleSearchSelectors.js
  app/repositories/base_query_builder.rb
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
  spec/javascripts/selectors/peopleSearchSelectorsSpec.js
  spec/support/helpers/query_builder_helper.rb
  spec/support/person_search_result_builder.rb
Labels: minor

#1153 SNAP-1057- Add 11-17 - Last Middle and First Name Query
  app/helpers/query_builder_helper.rb
  app/repositories/query_builder.rb
  app/services/person_search_by_last_middle_first_name_query_builder_part_one.rb
  app/services/person_search_by_last_middle_first_name_query_builder_part_three.rb
  app/services/person_search_by_last_middle_first_name_query_builder_part_two.rb
  spec/services/person_search_by_last_middle_first_name_query_builder_part_three_spec.rb
  spec/support/helpers/person_search_by_last_middle_first_name_query_builder_part_three_helper.rb
  spec/support/helpers/person_search_by_last_middle_first_name_query_builder_part_two_helper.rb
  spec/support/helpers/person_search_by_name_query_builder_helper.rb
  spec/support/person_search_result_builder.rb
Labels: minor

#1155 Fix for the approximate age drop down
  app/javascript/common/search/age/AgeNumberSelect.jsx
  spec/javascripts/components/common/search/age/AgeNumberSelectSpec.jsx
Labels: patch

#1156 Update last middle first name query
  app/services/person_search_by_last_middle_first_name_query_builder_part_one.rb
  app/services/person_search_by_last_middle_first_name_query_builder_part_two.rb
  spec/support/helpers/person_search_by_last_middle_first_name_query_builder_part_one_helper.rb
  spec/support/helpers/person_search_by_last_middle_first_name_query_builder_part_two_helper.rb
Labels: patch

#1157 rebuild tooltip
  app/javascript/common/search/SearchResultsTable.jsx
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
Labels: patch

#1158 Fix privilege
  app/javascript/common/search/SearchResultsTable.jsx
  spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
Labels: patch
